# Generated by Django 5.2.3 on 2025-06-11 16:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Participante',
            fields=[
                ('id_aluno', models.IntegerField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=100)),
                ('escola', models.CharField(max_length=100)),
                ('cpf', models.CharField(max_length=14, unique=True)),
                ('data', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Prova',
            fields=[
                ('id_prova', models.IntegerField(primary_key=True, serialize=False)),
                ('gabarito', models.CharField(max_length=100)),
                ('modalidade', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Resultado',
            fields=[
                ('id_resultado', models.AutoField(primary_key=True, serialize=False)),
                ('erro', models.IntegerField()),
                ('gabarito_res', models.CharField(max_length=100)),
                ('acertos', models.CharField(max_length=100)),
                ('nota', models.FloatField()),
                ('arquivo', models.CharField(max_length=200)),
                ('id_aluno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.participante')),
                ('id_prova', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.prova')),
            ],
        ),
    ]
