# Generated by Django 5.2.3 on 2025-06-14 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participante',
            name='data',
            field=models.CharField(max_length=20),
        ),
    ]
