# Generated by Django 5.2.3 on 2025-06-17 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Participante',
            fields=[
                ('id_aluno', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=100)),
                ('escola', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Prova',
            fields=[
                ('id_prova', models.AutoField(primary_key=True, serialize=False)),
                ('gabarito', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Resultado',
            fields=[
                ('id_resultado', models.AutoField(primary_key=True, serialize=False)),
                ('erro', models.IntegerField(blank=True, null=True)),
                ('gabarito_res', models.CharField(max_length=21)),
                ('acertos', models.CharField(max_length=10)),
                ('nota', models.FloatField()),
                ('id_prova', models.IntegerField()),
                ('id_aluno', models.IntegerField()),
                ('arquivo', models.FileField(upload_to='uploads/')),
            ],
        ),
    ]
